#!/bin/bash

set -e

# alias tpaexec='/home/ec2-user/tpa/bin/tpaexec'
# source ~/.virtualenvs/tpa/bin/activate
# cp -r cfg/BDR-Always-ON/commands .

tpaexec deprovision . || true
cp config.1.yml config.yml
tpaexec provision .
tpaexec relink . 
tpaexec deploy .

cp config.2.yml config.yml
tpaexec provision .
tpaexec upgrade . -e update_hosts=oltp01
tpaexec deploy .
tpaexec cmd . oltp01,orr01,oltp02,orr02,wit  -b --become-user enterprisedb -a 'psql -p 5444 bdrdb -c "SELECT current_setting($$server_version$$) AS server_version;"'

cp config.3.yml config.yml
tpaexec provision .
tpaexec upgrade . -e update_hosts=oltp02,orr02
tpaexec deploy .
tpaexec cmd . oltp01,orr01,oltp02,orr02,wit  -b --become-user enterprisedb -a 'psql -p 5444 bdrdb -c "SELECT current_setting($$server_version$$) AS server_version;"'

cp config.4.yml config.yml
tpaexec provision . 
tpaexec upgrade . -e update_hosts=orr01
tpaexec deploy .
tpaexec cmd . oltp01,orr01,oltp02,orr02,wit  -b --become-user enterprisedb -a 'psql -p 5444 bdrdb -c "SELECT current_setting($$server_version$$) AS server_version;"'

### optionally uncomment the following lines to clean up the old cluster and binaries
# tpaexec cmd . oltp01,orr01,oltp02,orr02,wit -a 'rm -rf /data01/epas13'
# tpaexec cmd . oltp01,orr01,oltp02,orr02,wit -a 'yum remove -y edb-as13-server*'

# tpaexec deprovision .
# rm config.yml

